//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWGLauncher.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SWGLauncher.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://discord.gg/UFQACtzed8.
        /// </summary>
        internal static string discordLink {
            get {
                return ResourceManager.GetString("discordLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap focusedDiscord {
            get {
                object obj = ResourceManager.GetObject("focusedDiscord", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;project_info&quot;: {
        ///    &quot;project_number&quot;: &quot;1088939217652&quot;,
        ///    &quot;firebase_url&quot;: &quot;https://project-stardust-4ba76-default-rtdb.firebaseio.com&quot;,
        ///    &quot;project_id&quot;: &quot;project-stardust-4ba76&quot;,
        ///    &quot;storage_bucket&quot;: &quot;project-stardust-4ba76.appspot.com&quot;
        ///  },
        ///  &quot;client&quot;: [
        ///    {
        ///      &quot;client_info&quot;: {
        ///        &quot;mobilesdk_app_id&quot;: &quot;1:1088939217652:android:5d4f24154afafbddfdc4a1&quot;,
        ///        &quot;android_client_info&quot;: {
        ///          &quot;package_name&quot;: &quot;SWG.Stardust&quot;
        ///        }
        ///      },
        ///      &quot;oauth_client&quot;: [
        ///        {
        ///          &quot;cl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string google_services {
            get {
                return ResourceManager.GetString("google_services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Project_Stardust {
            get {
                object obj = ResourceManager.GetObject("Project_Stardust", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap swg_stardust_logo {
            get {
                object obj = ResourceManager.GetObject("swg_stardust_logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap unfocusedDiscord {
            get {
                object obj = ResourceManager.GetObject("unfocusedDiscord", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
